# Configuration for an optional finance API integration.
# Replace the example values as needed.

# Root endpoint for API requests.
base_url: "https://example.com/api"

# Authentication token (leave blank if the API doesn't require one).
api_key: "your-api-key"

# Endpoint templates used by helper scripts.
# Placeholders:
#   {symbol} - ticker symbol
#   {period} - historical period (e.g., "1y").
endpoints:
  profile: "/v1/profile/{symbol}"                # Company profile endpoint.
  prices:  "/v1/prices/{symbol}?period={period}" # Historical prices endpoint.

